name: Lint

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  cppcheck:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install dependencies
        run: sudo apt install cppcheck
      - name: cppcheck
        run: make cppcheck

  cpplint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install dependencies
        run: sudo apt install cpplint
      - name: cpplint
        run: make cpplint
